project: satellite-imagery
description: Download and Visualize Satellite Imagery with SPAI
thumbnail: https://www.un-spider.org/sites/default/files/styles/downscale_to_676w_cut_to_273h/public/Ecosystem_services.jpg?itok=EbSqAdef

storage:
  - name: data
    type: s3
scripts:
  - name: downloader
# apis:
#   - name: xyz
#     port: 8030
# uis:
#   - name: map
#     command: streamlit run main.py --server.address 0.0.0.0 --server.port 80
#     # command: streamlit run main.py --server.address localhost
#     port: 8501
#     env:
#       XYZ_URL: api.xyz
